name: doc-deploy
on:
  push:
    branches:
      - master
jobs:
  doc-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
      - name: setup-doc
        run: |
          sudo apt-get update
          sudo apt install -yqq python3-sphinx python3-sphinx-rtd-theme
      - name: build-doc
        run: |
          make
          touch docs/.nojekyll
      - name: deploy-doc
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/
          CLEAN: true
